//go:build !ignore_autogenerated

/*
Copyright 2020 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterControlPlaneBinding) DeepCopyInto(out *ClusterControlPlaneBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterControlPlaneBinding.
func (in *ClusterControlPlaneBinding) DeepCopy() *ClusterControlPlaneBinding {
	if in == nil {
		return nil
	}
	out := new(ClusterControlPlaneBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterControlPlaneBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterControlPlaneBindingList) DeepCopyInto(out *ClusterControlPlaneBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterControlPlaneBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterControlPlaneBindingList.
func (in *ClusterControlPlaneBindingList) DeepCopy() *ClusterControlPlaneBindingList {
	if in == nil {
		return nil
	}
	out := new(ClusterControlPlaneBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterControlPlaneBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneBinding) DeepCopyInto(out *ControlPlaneBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneBinding.
func (in *ControlPlaneBinding) DeepCopy() *ControlPlaneBinding {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneBindingList) DeepCopyInto(out *ControlPlaneBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneBindingList.
func (in *ControlPlaneBindingList) DeepCopy() *ControlPlaneBindingList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneBindingSpec) DeepCopyInto(out *ControlPlaneBindingSpec) {
	*out = *in
	out.DefaultControlPlaneTarget = in.DefaultControlPlaneTarget
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]LooseControlPlaneTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneBindingSpec.
func (in *ControlPlaneBindingSpec) DeepCopy() *ControlPlaneBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneBindingStatus) DeepCopyInto(out *ControlPlaneBindingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneBindingStatus.
func (in *ControlPlaneBindingStatus) DeepCopy() *ControlPlaneBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneRef) DeepCopyInto(out *ControlPlaneRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneRef.
func (in *ControlPlaneRef) DeepCopy() *ControlPlaneRef {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneTarget) DeepCopyInto(out *ControlPlaneTarget) {
	*out = *in
	out.IdentitySecretRef = in.IdentitySecretRef
	out.SpaceConfigSecretRef = in.SpaceConfigSecretRef
	out.ControlPlaneRef = in.ControlPlaneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneTarget.
func (in *ControlPlaneTarget) DeepCopy() *ControlPlaneTarget {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LooseControlPlaneTarget) DeepCopyInto(out *LooseControlPlaneTarget) {
	*out = *in
	in.SourceSelector.DeepCopyInto(&out.SourceSelector)
	if in.IdentitySecretRef != nil {
		in, out := &in.IdentitySecretRef, &out.IdentitySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SpaceConfigSecretRef != nil {
		in, out := &in.SpaceConfigSecretRef, &out.SpaceConfigSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ControlPlaneRef != nil {
		in, out := &in.ControlPlaneRef, &out.ControlPlaneRef
		*out = new(ControlPlaneRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LooseControlPlaneTarget.
func (in *LooseControlPlaneTarget) DeepCopy() *LooseControlPlaneTarget {
	if in == nil {
		return nil
	}
	out := new(LooseControlPlaneTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSelector) DeepCopyInto(out *SourceSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSelector.
func (in *SourceSelector) DeepCopy() *SourceSelector {
	if in == nil {
		return nil
	}
	out := new(SourceSelector)
	in.DeepCopyInto(out)
	return out
}
